In [1]:
import numpy as np
K = 5  # Number of prototypes
d = 3  # Dimensionality of each prototype
prototypes = np.random.randn(K, d)
print(prototypes)

[[ 1.43022828 -0.82901025  0.23412048]
 [-1.54922254  0.20158991  0.43450656]
 [-0.15043671  1.21223657  1.55879118]
 [-0.64106057 -1.96934269 -0.11769164]
 [-1.21210867  0.10824211  0.85231027]]


In [ ]:
rng = np.random.default_rng(42)


Generator(PCG64)


In [2]:
import numpy as np

def decision_tree_mapping(x_parents, random_state=None):
    """
    用随机决策树实现 node value 映射
    参数:
        x_parents: np.array of shape (n_samples, n_features) — 父节点的输入值
    返回:
        x_current: np.array of shape (n_samples,) — 当前节点的值
    """
    rng = np.random.default_rng(random_state)
    n_samples, n_features = x_parents.shape
    
    # 随机选择要分裂的特征
    feature_idx = rng.choice(n_features)
    
    # 设定一个随机阈值（基于该特征的分布）
    feature_values = x_parents[:, feature_idx]
    threshold = rng.uniform(np.min(feature_values), np.max(feature_values))

    # 决策输出值（叶子节点值）
    output_low = rng.normal(loc=-1.0, scale=0.5)   # 如果小于等于阈值
    output_high = rng.normal(loc=1.0, scale=0.5)   # 如果大于阈值

    # 根据决策分配输出
    decision_mask = feature_values > threshold
    x_current = np.where(decision_mask, output_high, output_low)

    return x_current

# 假设 parent nodes 是 x1 和 x2
n_samples = 10
x1 = np.random.normal(0, 1, size=n_samples)
x2 = np.random.uniform(-2, 2, size=n_samples)

# 合并成父节点输入
X_parents = np.stack([x1, x2], axis=1)

# 生成当前节点的值 x3
x3 = decision_tree_mapping(X_parents, random_state=42)

print("父节点 x1:\n", x1)
print("父节点 x2:\n", x2)
print("当前节点 x3:\n", x3)

父节点 x1:
 [ 0.27398496  1.71626235 -1.16413865  0.35196854  0.97618944 -0.89387484
 -0.88856678  0.45520962  0.95093451 -0.7790333 ]
父节点 x2:
 [-0.93365601  0.45020157 -1.80694458 -1.37865652  1.5244307   1.76994311
  1.04239972  1.01008812 -0.5590318   0.48002944]
当前节点 x3:
 [ 1.47028236  1.47028236 -0.6247744   1.47028236  1.47028236 -0.6247744
 -0.6247744   1.47028236  1.47028236 -0.6247744 ]
